PR: fixing repo clone

diff --git a/.github/workflows/pr_from_upstream.yml b/.github/workflows/pr_from_upstream.yml
--- a/.github/workflows/pr_from_upstream.yml
+++ b/.github/workflows/pr_from_upstream.yml
@@ -19,13 +19,22 @@ jobs:
           git checkout "${{ github.ref_name }}"
           git branch --set-upstream-to=upstream/${{ github.ref_name }} ${{ github.ref_name }}
 
-      # - name: Generate a token for Rekku
-      #   id: generate-rekku-token
-      #   uses: actions/create-github-app-token@v1
-      #   with:
-      #     app-id: ${{ vars.REKKU_APP_ID }}
-      #     private-key: ${{ secrets.REKKU_PRIVATE_KEY }}
-      #     owner: "RetroDECK"
+      - name: Debug Private Key
+        run: |
+          echo "Testing access to REKKU_PRIVATE_KEY"
+          if [ -z "${{ secrets.REKKU_PRIVATE_KEY }}" ]; then
+            echo "Error: secret REKKU_PRIVATE_KEY not available."
+            exit 1
+          fi
+          echo "Secret REKKU_PRIVATE_KEY available."
+
+      - name: Generate a token for Rekku
+        id: generate-rekku-token
+        uses: actions/create-github-app-token@v1
+        with:
+          app-id: ${{ vars.REKKU_APP_ID }}
+          private-key: ${{ secrets.REKKU_PRIVATE_KEY }}
+          owner: "RetroDECK"
 
       - name: Configuring Git
         run: |
